name: Auto Assign

on:
  pull_request:
    types: [opened, ready_for_review]

jobs:
  auto-assign:
    runs-on: ubuntu-latest

    steps:
      - name: Auto assign reviewer
        uses: kentaro-m/auto-assign-action@v2
        with:
          configuration-path: .github/auto_assign.yml
